#
# https://github.com/jp-gouin/helm-openldap/tree/master/.bin
#
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
    - hostPath: /tmp/kind-worker
      containerPath: /tmp/kind-worker
  labels:
    backend: sql
- role: worker
- role: worker
