#!/bin/sh

# Determine pod's cluster name
pod_name="${POD_NAME:-$(hostname -s)}" # e.g. pod-0
pod_endpoint_name="$(hostname -f)" # e.g. pod-0.servicename.namespace.svc.cluster.local
sts_name="$(echo $pod_name | sed 's|-[0-9]\+||g')"

[ -z "$ERLANG_NODE_ARG" ] && export ERLANG_NODE_ARG="$sts_name@$pod_endpoint_name"
export CONFIG_DIR="$HOME"/conf
export LOGS_DIR="$HOME"/logs
export SPOOL_DIR="$HOME"/database

exec $(find /opt -name ejabberdctl) "$@"
