apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: try-workflow-serial
spec:
  entry: serial-of-3-node
  templates:
    - name: serial-of-3-node
      templateType: Parallel
      deadline: 240s
      children:
        # - suspending
        - workflow-network-chaos
        - workflow-stress-chaos
        - workflow-pod-chaos
    # - name: suspending
    #   templateType: Suspend
    #   deadline: 10s
    - name: workflow-network-chaos
      templateType: NetworkChaos
      deadline: 20s
      networkChaos:
        direction: to
        action: delay
        mode: all
        selector:
          labelSelectors:
            'app.kubernetes.io/name': 'ejabberd'
        delay:
          latency: '90ms'
          correlation: '25'
          jitter: '90ms'
    - name: workflow-stress-chaos
      templateType: StressChaos
      deadline: 20s
      stressChaos:
        mode: one
        selector:
          labelSelectors:
            'app.kubernetes.io/name': 'ejabberd'
        stressors:
          cpu:
            workers: 1
            load: 20
            options: ['--cpu 1', '--timeout 600']
    - name: workflow-pod-chaos
      templateType: PodChaos
      deadline: 20s
      podChaos:
        action: pod-kill
        mode: one
        selector:
          labelSelectors:
            'app.kubernetes.io/name': 'ejabberd'
