{{- if .Values.sqlDatabase.enabled }}
{{- if .Values.sqlDatabase.flyway.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ejabberd.fullname" . }}-sql-migration
  namespace: {{ template "ejabberd.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway
          args:
            - info
            {{- if .Values.sqlDatabase.flyway.baselineVersion }}
            - baseline
            - info
            {{- end }}
            - repair
            - migrate
            - info
          volumeMounts:
            - mountPath: /flyway/sql
              name: sql
            - mountPath: /flyway/conf
              name: config
            {{- if (eq (toString .Values.sqlDatabase.config.sql_type) "sqlite") }}
            - mountPath: {{ default "/opt/ejabberd/sqlite/ejabberd.db" .Values.sqlDatabase.config.sql_database }}
              subPath: {{ default "ejabberd.db" .Values.sqlDatabase.sqlite.fileName }}
              name: {{ include "ejabberd.fullname" . }}-sqlite
            {{- end }}
      volumes:
        - name: sql
          configMap:
            {{- if .Values.sqlDatabase.newSqlSchema }}
            name: {{ include "ejabberd.fullname" . }}-{{ default "pgsql" .Values.sqlDatabase.config.sql_type }}-new
            {{ else }}
            name: {{ include "ejabberd.fullname" . }}-{{ default "pgsql" .Values.sqlDatabase.config.sql_type }}-default
            {{- end }}
        - name: config
          secret:
            secretName: {{ include "ejabberd.fullname" . }}-flyway-config
        {{- if (eq (toString .Values.sqlDatabase.config.sql_type) "sqlite") }}
        - name: {{ include "ejabberd.fullname" . }}-sqlite
          persistentVolumeClaim:
            {{- if .Values.sqlDatabase.sqlite.existingClaim }}
            claimName: {{ default "ejabberd-sqlite" .Values.sqlDatabase.sqlite.existingClaim }}
            {{ else }}
            claimName: {{ include "ejabberd.fullname" . }}-sqlite
            {{- end }}
        {{- end }}
      restartPolicy: Never
{{- end }}
{{- end }}
